### ISSUE TITLE
Wrong context path for service indexer in build-all.yaml

### ISSUE THREAD

**Issue by stlozhaw** [sustainability-zhaw/integration-test#1]
https://github.com/sustainability-zhaw/integration-test/blob/1734c90c63087c95a15556acd84e9748056c750a/build-all.yaml#L89-L91

Should be:
```yaml
indexer: 
    build:
      context: ../sdg-indexer/  
```
